name: ml-course-day1
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - jupyter
  - jupyterlab=3.4
  - matplotlib
  - numpy=1.24.2
  - pytorch=2.0.1
  - cpuonly
  - scipy=1.9
  - seaborn=0.12
  - ipython=8.15
